export enum CONTENT_TYPE {
    USER = 'USER',
    PAGE = 'PAGE',
    POST = 'POST'
}

export enum CONTENT_ACTION {
    BLOCK_CREATE = 'BLOCK_CREATE',
    BLOCK_DELETE = 'BLOCK_DELETE',
    HIDDEN_CREATE = 'HIDDEN_CREATE',
    HIDDEN_REMOVE = 'HIDDEN_REMOVE'
}